### ISSUE TITLE
Extras page bug

### ISSUE THREAD

**Issue by weeder** [oNdsen/OGP_SBS#3]
Hi 
You was right with previous issue.The problem caused by cloudflare cache.
http://prntscr.com/fkd6xo
Here is another one.
On extras page Download/Update not visible bcs of colors it have
Also dont want to update.
I updated few with another theme just to check.
Thx for help

**Comment by oNdsen** [comment]
there is no bug like that. check again your cache.
maybe you can check your cloudflare config.

**Comment by FarukGamer** [comment]
Cache everything you want but not the panel! This can lead to unexpected problems.
