### ISSUE TITLE
Tiled background image

### ISSUE THREAD

**Issue by weeder** [oNdsen/OGP_SBS#4]
Hi 
Can you please put there a checkbox for tiled background images?
Regarding to previous issue Cloudflare use like 3 hr cache.So when it expire the changes show up anyway on website.But dont tell me that you can read what is writen in that silver box with white letters, without selecting text in it.
It dont want to update anyway.Othere themes doing it.
There is a development mode on cloudflare so i testing your theme live from server after this.
Thx to pointing me on it.

**Comment by oNdsen** [comment]
what do you want?
please add some screenshots.

**Comment by oNdsen** [comment]
this is not an issue. if you have suggestions, post it at ogp forums.
