### ISSUE TITLE
bug in Upload file section

### ISSUE THREAD

**Issue by nksiddhant** [oNdsen/OGP_SBS#5]
Hi I tried to upload file, it uploaded but without any progress bar nor the upload file window disappear it remains on screen till i press close button.

**Comment by oNdsen** [comment]
where?

**Comment by nksiddhant** [comment]
here 
![theme err](https://user-images.githubusercontent.com/18354338/27511752-ced0ecec-5949-11e7-868e-8a001545b434.jpg)

**Comment by oNdsen** [comment]
Its not a Theme Bug. Its a general OGP Bug.
